#!/usr/bin/env python3
# Copyright (c) 2026 UniBlake Developers
#
# Regenerate tests/kat_blake2b.h from the BLAKE2 reference package's published
# vectors. The input is testvectors/blake2-kat.json in a clone of
# github.com/BLAKE2/BLAKE2; pass its path.
#
#   python3 tests/gen_kat.py /path/to/BLAKE2/testvectors/blake2-kat.json
#
# The vectors are input lengths 0..255, each unkeyed and keyed with the
# 64-byte sequential key 00,01,..,3f, all producing 64-byte digests. The
# generated header stores them as three flat byte arrays indexed by length,
# which is smaller and faster to scan than a struct per case.

import json
import sys


def blob(name, hex_items):
    out = ["static const uint8_t %s[] = {" % name]
    flat = "".join(hex_items)
    row = []
    for i in range(0, len(flat), 2):
        row.append("0x" + flat[i:i + 2])
        if len(row) == 12:
            out.append("  " + ",".join(row) + ",")
            row = []
    if row:
        out.append("  " + ",".join(row) + ",")
    out.append("};")
    return "\n".join(out)


def main(path):
    vectors = [v for v in json.load(open(path)) if v["hash"] == "blake2b"]
    unkeyed = sorted((v for v in vectors if not v["key"]),
                     key=lambda v: len(v["in"]))
    keyed = sorted((v for v in vectors if v["key"]),
                   key=lambda v: len(v["in"]))

    # The test indexes by input length, so the set must be exactly 0..N-1.
    for i, v in enumerate(unkeyed):
        assert len(v["in"]) // 2 == i, "unkeyed vectors are not 0..N-1"
    for i, v in enumerate(keyed):
        assert len(v["in"]) // 2 == i, "keyed vectors are not 0..N-1"
    assert len({v["key"] for v in keyed}) == 1, "keyed vectors use >1 key"
    assert all(len(v["out"]) // 2 == 64 for v in vectors), "digest not 64 B"

    lines = [
        "/* BLAKE2b known-answer vectors.",
        " *",
        " * Derived data, not our work: the digests are the BLAKE2 authors'"
        " published",
        " * answers, extracted from testvectors/blake2-kat.json in the"
        " reference",
        " * package at github.com/BLAKE2/BLAKE2, upstream pin ed1974e."
        " Copyright 2012",
        " * Samuel Neves; CC0 1.0 / OpenSSL / Apache-2.0, at the user's"
        " option.",
        " *",
        " * %d cases: input lengths 0..%d, each unkeyed and with the 64-byte"
        % (len(unkeyed), len(unkeyed) - 1),
        " * sequential key 00,01,..,3f. All digests are 64 bytes.",
        " *",
        " * Generated by tests/gen_kat.py. Do not edit by hand. */",
        "",
        "#define UB_KAT_COUNT %d" % len(unkeyed),
        "#define UB_KAT_OUTLEN 64",
        "",
        blob("ub_kat_key", [keyed[0]["key"]]),
        "",
        blob("ub_kat_unkeyed", [v["out"] for v in unkeyed]),
        "",
        blob("ub_kat_keyed", [v["out"] for v in keyed]),
    ]
    sys.stdout.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit("usage: gen_kat.py <blake2-kat.json>")
    main(sys.argv[1])
